In [44]:
import numpy as np
import keras
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense

In [45]:
concrete_data = pd.read_csv('https://ibm.box.com/shared/static/svl8tu7cmod6tizo6rk0ke4sbuhtpdfx.csv')
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [46]:
concrete_data.shape

(1030, 9)

In [47]:
# check missing values
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [54]:
# split data into predictors and target
concrete_data_columns = concrete_data.columns

# all data except strength
predictors = concrete_data[concrete_data_columns[concrete_data_columns !='Strength']]
target = concrete_data['Strength']

In [55]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [60]:
# normalize the values in the predictors
predictors_norm = (predictors-predictors.min())/(predictors.max()-predictors.min())
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,1.000000,0.000000,0.0,0.321086,0.07764,0.694767,0.205720,0.074176
1,1.000000,0.000000,0.0,0.321086,0.07764,0.738372,0.205720,0.074176
2,0.526256,0.396494,0.0,0.848243,0.00000,0.380814,0.000000,0.739011
3,0.526256,0.396494,0.0,0.848243,0.00000,0.380814,0.000000,1.000000
4,0.220548,0.368392,0.0,0.560703,0.00000,0.515698,0.580783,0.986264

In [89]:
n_cols = predictors_norm.shape[1]   # number of predictors

In [98]:
# build a neural network
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(50, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [99]:
# train and test the network
# build the network
model = regression_model()

# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Train on 721 samples, validate on 309 samples
Epoch 1/100
 - 1s - loss: 1655.0981 - val_loss: 1157.3103
Epoch 2/100
 - 0s - loss: 1543.8646 - val_loss: 1014.6224
Epoch 3/100
 - 0s - loss: 1298.1530 - val_loss: 729.6131
Epoch 4/100
 - 0s - loss: 871.3988 - val_loss: 352.2317
Epoch 5/100
 - 0s - loss: 432.8433 - val_loss: 179.2392
Epoch 6/100
 - 0s - loss: 285.1755 - val_loss: 203.2084
Epoch 7/100
 - 0s - loss: 271.7214 - val_loss: 183.4643
Epoch 8/100
 - 0s - loss: 258.7986 - val_loss: 173.5826
Epoch 9/100
 - 0s - loss: 246.7856 - val_loss: 167.7467
Epoch 10/100
 - 0s - loss: 235.2817 - val_loss: 159.5382
Epoch 11/100
 - 0s - loss: 224.0046 - val_loss: 153.1168
Epoch 12/100
 - 0s - loss: 212.9195 - val_loss: 145.0505
Epoch 13/100
 - 0s - loss: 202.1147 - val_loss: 142.3042
Epoch 14/100
 - 0s - loss: 192.4364 - val_loss: 134.4264
Epoch 15/100
 - 0s - loss: 181.9087 - val_loss: 124.4226
Epoch 16/100
 - 0s - loss: 173.3533 - val_loss: 121.4510
Epoch 17/100
 - 0s - loss: 165.1753 - val_loss: 112.3108
Epoch 18/100
 - 0s - loss: 157.3868 - val_loss: 111.6466
Epoch 19/100
 - 0s - loss: 151.1145 - val_loss: 106.0519
Epoch 20/100
 - 0s - loss: 145.7848 - val_loss: 104.3290
Epoch 21/100
 - 0s - loss: 141.4908 - val_loss: 102.0606
Epoch 22/100
 - 0s - loss: 137.9246 - val_loss: 99.6231
Epoch 23/100
 - 0s - loss: 135.6793 - val_loss: 97.3952
Epoch 24/100
 - 0s - loss: 133.0646 - val_loss: 96.4284
Epoch 25/100
 - 0s - loss: 131.5720 - val_loss: 95.9472
Epoch 26/100
 - 0s - loss: 129.7935 - val_loss: 96.6363
Epoch 27/100
 - 0s - loss: 129.1382 - val_loss: 93.7463
Epoch 28/100
 - 0s - loss: 128.1198 - val_loss: 94.9316
Epoch 29/100
 - 0s - loss: 127.4092 - val_loss: 94.5584
Epoch 30/100
 - 0s - loss: 126.1090 - val_loss: 91.4243
Epoch 31/100
 - 0s - loss: 126.0220 - val_loss: 93.2020
Epoch 32/100
 - 0s - loss: 125.3475 - val_loss: 91.5771
Epoch 33/100
 - 0s - loss: 125.2448 - val_loss: 94.6278
Epoch 34/100
 - 0s - loss: 124.3341 - val_loss: 92.8832
Epoch 35/100
 - 0s - loss: 123.3254 - val_loss: 93.4503
Epoch 36/100
 - 0s - loss: 122.8609 - val_loss: 90.5049
Epoch 37/100
 - 0s - loss: 122.3496 - val_loss: 89.5179
Epoch 38/100
 - 0s - loss: 121.3519 - val_loss: 88.3831
Epoch 39/100
 - 0s - loss: 121.4860 - val_loss: 86.7943
Epoch 40/100
 - 0s - loss: 120.2552 - val_loss: 88.5599
Epoch 41/100
 - 0s - loss: 119.4888 - val_loss: 90.1050
Epoch 42/100
 - 0s - loss: 118.7508 - val_loss: 87.5048
Epoch 43/100
 - 0s - loss: 118.6163 - val_loss: 83.9739
Epoch 44/100
 - 0s - loss: 117.6175 - val_loss: 87.5519
Epoch 45/100
 - 0s - loss: 116.9645 - val_loss: 87.2330
Epoch 46/100
 - 0s - loss: 116.0883 - val_loss: 86.1048
Epoch 47/100
 - 0s - loss: 115.4647 - val_loss: 87.0046
Epoch 48/100
 - 0s - loss: 115.1654 - val_loss: 85.7458
Epoch 49/100
 - 0s - loss: 113.4344 - val_loss: 83.4330
Epoch 50/100
 - 0s - loss: 112.9051 - val_loss: 80.8125
Epoch 51/100
 - 0s - loss: 111.6060 - val_loss: 81.7368
Epoch 52/100
 - 0s - loss: 110.4386 - val_loss: 79.5439
Epoch 53/100
 - 0s - loss: 109.4989 - val_loss: 83.0124
Epoch 54/100
 - 0s - loss: 109.0488 - val_loss: 77.9548
Epoch 55/100
 - 0s - loss: 107.5164 - val_loss: 79.5284
Epoch 56/100
 - 0s - loss: 106.5930 - val_loss: 79.8350
Epoch 57/100
 - 0s - loss: 105.6629 - val_loss: 78.0954
Epoch 58/100
 - 0s - loss: 104.1416 - val_loss: 78.3471
Epoch 59/100
 - 0s - loss: 102.6243 - val_loss: 75.3180
Epoch 60/100
 - 0s - loss: 101.7389 - val_loss: 75.6327
Epoch 61/100
 - 0s - loss: 100.5667 - val_loss: 78.3680
Epoch 62/100
 - 0s - loss: 100.4969 - val_loss: 74.4399
Epoch 63/100
 - 0s - loss: 98.8328 - val_loss: 72.8167
Epoch 64/100
 - 0s - loss: 97.8936 - val_loss: 71.7096
Epoch 65/100
 - 0s - loss: 98.5781 - val_loss: 73.3538
Epoch 66/100
 - 0s - loss: 95.6420 - val_loss: 76.8462
Epoch 67/100
 - 0s - loss: 93.9901 - val_loss: 72.4002
Epoch 68/100
 - 0s - loss: 92.5943 - val_loss: 73.1903
Epoch 69/100
 - 0s - loss: 92.5507 - val_loss: 70.0475
Epoch 70/100
 - 0s - loss: 90.7379 - val_loss: 69.8777
Epoch 71/100
 - 0s - loss: 89.4671 - val_loss: 73.1194
Epoch 72/100
 - 0s - loss: 88.4001 - val_loss: 67.5943
Epoch 73/100
 - 0s - loss: 88.2591 - val_loss: 75.0693
Epoch 74/100
 - 0s - loss: 87.3800 - val_loss: 66.7281
Epoch 75/100
 - 0s - loss: 85.2391 - val_loss: 68.6209
Epoch 76/100
 - 0s - loss: 84.6348 - val_loss: 65.4917
Epoch 77/100
 - 0s - loss: 83.8009 - val_loss: 66.6970
Epoch 78/100
 - 0s - loss: 82.6072 - val_loss: 64.8348
Epoch 79/100
 - 0s - loss: 81.9803 - val_loss: 66.9184
Epoch 80/100
 - 0s - loss: 81.0722 - val_loss: 63.1947
Epoch 81/100
 - 0s - loss: 80.7081 - val_loss: 66.8829
Epoch 82/100
 - 0s - loss: 79.5075 - val_loss: 64.2967
Epoch 83/100
 - 0s - loss: 79.2987 - val_loss: 68.2449
Epoch 84/100
 - 0s - loss: 78.1218 - val_loss: 65.4721
Epoch 85/100
 - 0s - loss: 77.1754 - val_loss: 61.3776
Epoch 86/100
 - 0s - loss: 75.4582 - val_loss: 63.4886
Epoch 87/100
 - 0s - loss: 75.0988 - val_loss: 61.6111
Epoch 88/100
 - 0s - loss: 74.0235 - val_loss: 61.6095
Epoch 89/100
 - 0s - loss: 73.3971 - val_loss: 65.6565
Epoch 90/100
 - 0s - loss: 72.5046 - val_loss: 62.3256
Epoch 91/100
 - 0s - loss: 71.0738 - val_loss: 58.2847
Epoch 92/100
 - 0s - loss: 70.9524 - val_loss: 63.3897
Epoch 93/100
 - 0s - loss: 69.7387 - val_loss: 58.4283
Epoch 94/100
 - 0s - loss: 70.6400 - val_loss: 59.0187
Epoch 95/100
 - 0s - loss: 69.7001 - val_loss: 62.9856
Epoch 96/100
 - 0s - loss: 67.8475 - val_loss: 61.0168
Epoch 97/100
 - 0s - loss: 66.3579 - val_loss: 59.8166
Epoch 98/100
 - 0s - loss: 65.6978 - val_loss: 58.0702
Epoch 99/100
 - 0s - loss: 65.3626 - val_loss: 61.5612
Epoch 100/100
 - 0s - loss: 64.2430 - val_loss: 60.5218

In [100]:
model.evaluate(predictors_norm, target)

1030/1030 [==============================] - 0s 21us/step

62.70344667342103